name: JupyterKernel
version: 1.0
date: 2018-10-05
description: |
    Jupyter kernel written in GAP

authors:
    - name: Markus Pfeiffer
      url: https://markusp.morphism.de/

maintainers:
    - name: Markus Pfeiffer
      url: https://markusp.morphism.de/

GAP: ">= 4.10"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "io"
      version: ">= 4.5.4"
      url: "https://gap-packages.github.io/io"
    - name: "json"
      version: ">= 2.0.0"
      url: "https://gap-packages.github.io/json/"
    - name: "uuid"
      version: ">= 0.6"
      url: "https://gap-packages.github.io/uuid/"
    - name: "ZeroMQInterface"
      version: ">= 0.10"
      url: "https://gap-packages.github.io/ZeroMQInterface/"
    - name: "crypting"
      version: ">= 0.9"
      url: "https://gap-packages.github.io/crypting/"

www: https://gap-packages.github.io/JupyterKernel/
readme: README.md
packageinfo: https://gap-packages.github.io/JupyterKernel/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/JupyterKernel/releases/download/v1.0/JupyterKernel-1.0.tar.gz

abstract: |
    The <span class="pkgname">JupyterKernel</span> package provides a so-called kernel for the Jupyter interactive document system.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    Jupyter, User Interface.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Pfe18</span>]   <b class='BibAuthor'>Pfeiffer, M.</b>,
     <i class='BibTitle'>JupyterKernel, Jupyter kernel written in GAP,
             Version 1.0</i>
     (<span class='BibYear'>2018</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/JupyterKernel/">https://gap-packages.github.io/JupyterKernel/</a></span>.
    </p>
    

bibtex: |
    @misc{ JupyterKernel1.0,
      author =           {Pfeiffer, M.},
      title =            {{JupyterKernel}, Jupyter kernel written in GAP, {V}ersion 1.0},
      month =            {Oct},
      year =             {2018},
      note =             {GAP package},
      howpublished =     {\href             {https://gap-packages.github.io/JupyterKernel/}             {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{JupyterKernel/}}},
      keywords =         {Jupyter; User Interface},
      printedkey =       {Pfe18}
    }

